events {
  worker_connections 1024;
}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location /v1/graphql {
      proxy_pass http://host.docker.internal:20247;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
      proxy_set_header Host $host;
    }

    location /user/ {
      proxy_pass http://host.docker.internal:20248;
      proxy_set_header Host $host;
    }

    location /file/ {
      proxy_pass http://host.docker.internal:20248;
      proxy_set_header Host $host;
      client_max_body_size 100M;
    }

    location /email/ {
      proxy_pass http://host.docker.internal:20248;
      proxy_set_header Host $host;
    }

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
